# Static CRT: the exe runs on a clean Windows install without the
# VC++ redistributable, which keeps "download one file" honest.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
